version: "3"

services:
  db:
    image: postgres
  backend:
    build: .
    command: bash -c "chmod +x wait_for_databases.sh
      && python3 manage.py makemigrations
      && python3 manage.py migrate
      && python3 manage.py migrate --run-syncdb
      && python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
